server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      enabled: false

spring:
  jdbc:
    template:
      max-rows: 1000
  # 工作流相关的配置
  activiti:
    database-schema-update: true
    check-process-definitions: true
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti6unit?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root